version: '2'
services:
  nginx:
    build: .
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
        - "./html/:/etc/nginx/html/"
        - "./keys/:/etc/nginx/mykeys/"
